### ISSUE TITLE
Add command to check uuid pattern

### ISSUE THREAD

**Issue by samit22** [samit22/uuid#6]
Command: uuid check <uuid>
This should check UUID pattern and return valid/invalid.

**Comment by norbinsh** [comment]
mind if i take this one @samit22?

can either validate using regex (slower) or through https://godoc.org/github.com/google/uuid#Parse (add dependency).

thoughts?

**Comment by samit22** [comment]
Sure @Norbinsh, I would say regex. Less dependency.

**Comment by norbinsh** [comment]
Sounds good.
I noticed you already have the pattern as part of your [existing test](https://github.com/samit22/uuid/blob/main/generator/uuidv4_test.go#L9), if you are happy with it, we can use the same.

Could you please confirm I am aligned with the intent here:

We want to add a new command, which the user will have to provide input to (the UUID to check), and it will return true/false depending on whether there was a match.

The below will return true
`uuid check 825926d4-9c30-4230-8467-5147dbbf3d25`

While the below will return false
`uuid check 825926d49c30423084675147dbbf3d25`

**Comment by samit22** [comment]
> Sounds good.
> I noticed you already have the pattern as part of your [existing test](https://github.com/samit22/uuid/blob/main/generator/uuidv4_test.go#L9), if you are happy with it, we can use the same.

We can use the same pattern.

> 
> Could you please confirm I am aligned with the intent here:
> 
> We want to add a new command, which the user will have to provide input to (the UUID to check), and it will return true/false depending on whether there was a match.
> 
> The below will return true
> `uuid check 825926d4-9c30-4230-8467-5147dbbf3d25`
> 
> While the below will return false
> `uuid check 825926d49c30423084675147dbbf3d25`



Yeah, that's right, I'm also thinking to add support for multiple arguments and return true false for each, I leave that up to you.

**Comment by samit22** [comment]
Fixed by #12
