### ISSUE TITLE
Add command for generate Nil/Empty UUID

### ISSUE THREAD

**Issue by samit22** [samit22/uuid#9]
Add command which generated empty uuid 00000000-0000-0000-0000-000000000000

Command `uuid empty` it should also support `uuid nil`

**Comment by slomek** [comment]
I'd love to take a crack on this, if possible 😉

**Comment by samit22** [comment]
> I'd love to take a crack on this, if possible 😉

Sure.

**Comment by samit22** [comment]
Closed by #10
